/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  StakeTransferer,
  StakeTransfererInterface,
} from "../StakeTransferer";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "transferTo",
        type: "address",
      },
    ],
    name: "exitAndTransfer",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    name: "receiversWhitelist",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_receiver",
        type: "address",
      },
      {
        internalType: "bool",
        name: "_whitelisted",
        type: "bool",
      },
    ],
    name: "setReceiverWhitelisted",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class StakeTransferer__factory {
  static readonly abi = _abi;
  static createInterface(): StakeTransfererInterface {
    return new utils.Interface(_abi) as StakeTransfererInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): StakeTransferer {
    return new Contract(address, _abi, signerOrProvider) as StakeTransferer;
  }
}
