/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IStakeTransferer,
  IStakeTransfererInterface,
} from "../IStakeTransferer";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "receiver",
        type: "address",
      },
      {
        internalType: "bool",
        name: "whitelisted",
        type: "bool",
      },
    ],
    name: "setReceiverWhitelisted",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IStakeTransferer__factory {
  static readonly abi = _abi;
  static createInterface(): IStakeTransfererInterface {
    return new utils.Interface(_abi) as IStakeTransfererInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IStakeTransferer {
    return new Contract(address, _abi, signerOrProvider) as IStakeTransferer;
  }
}
