/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  ITreasuryOperated,
  ITreasuryOperatedInterface,
} from "../ITreasuryOperated";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "reward",
        type: "uint256",
      },
    ],
    name: "notifyExternalReward",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "withdrawStake",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class ITreasuryOperated__factory {
  static readonly abi = _abi;
  static createInterface(): ITreasuryOperatedInterface {
    return new utils.Interface(_abi) as ITreasuryOperatedInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ITreasuryOperated {
    return new Contract(address, _abi, signerOrProvider) as ITreasuryOperated;
  }
}
