/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { StakeLock, StakeLockInterface } from "../StakeLock";

const _abi = [
  {
    inputs: [],
    name: "lockEndTimestamp",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class StakeLock__factory {
  static readonly abi = _abi;
  static createInterface(): StakeLockInterface {
    return new utils.Interface(_abi) as StakeLockInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): StakeLock {
    return new Contract(address, _abi, signerOrProvider) as StakeLock;
  }
}
