/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface StakeTransfererInterface extends utils.Interface {
  functions: {
    "exitAndTransfer(address)": FunctionFragment;
    "receiversWhitelist(address)": FunctionFragment;
    "setReceiverWhitelisted(address,bool)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "exitAndTransfer",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "receiversWhitelist",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "setReceiverWhitelisted",
    values: [string, boolean]
  ): string;

  decodeFunctionResult(
    functionFragment: "exitAndTransfer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "receiversWhitelist",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setReceiverWhitelisted",
    data: BytesLike
  ): Result;

  events: {};
}

export interface StakeTransferer extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: StakeTransfererInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    exitAndTransfer(
      transferTo: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    receiversWhitelist(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    setReceiverWhitelisted(
      _receiver: string,
      _whitelisted: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  exitAndTransfer(
    transferTo: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  receiversWhitelist(arg0: string, overrides?: CallOverrides): Promise<boolean>;

  setReceiverWhitelisted(
    _receiver: string,
    _whitelisted: boolean,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    exitAndTransfer(
      transferTo: string,
      overrides?: CallOverrides
    ): Promise<void>;

    receiversWhitelist(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    setReceiverWhitelisted(
      _receiver: string,
      _whitelisted: boolean,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    exitAndTransfer(
      transferTo: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    receiversWhitelist(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    setReceiverWhitelisted(
      _receiver: string,
      _whitelisted: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    exitAndTransfer(
      transferTo: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    receiversWhitelist(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    setReceiverWhitelisted(
      _receiver: string,
      _whitelisted: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
