/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "./common";

export interface TreasuryOperatedInterface extends ethers.utils.Interface {
  functions: {
    "externalRewards(address)": FunctionFragment;
    "treasury()": FunctionFragment;
    "withdrawStake(uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "externalRewards",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "treasury", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "withdrawStake",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "externalRewards",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "treasury", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdrawStake",
    data: BytesLike
  ): Result;

  events: {
    "ExternalRewardsAdded(address,address,uint256)": EventFragment;
    "ExternalRewardsClaimed(address)": EventFragment;
    "StakeWithdrawn(uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "ExternalRewardsAdded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ExternalRewardsClaimed"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "StakeWithdrawn"): EventFragment;
}

export type ExternalRewardsAddedEvent = TypedEvent<
  [string, string, BigNumber],
  { from: string; token: string; reward: BigNumber }
>;

export type ExternalRewardsAddedEventFilter =
  TypedEventFilter<ExternalRewardsAddedEvent>;

export type ExternalRewardsClaimedEvent = TypedEvent<
  [string],
  { receiver: string }
>;

export type ExternalRewardsClaimedEventFilter =
  TypedEventFilter<ExternalRewardsClaimedEvent>;

export type StakeWithdrawnEvent = TypedEvent<
  [BigNumber],
  { amount: BigNumber }
>;

export type StakeWithdrawnEventFilter = TypedEventFilter<StakeWithdrawnEvent>;

export interface TreasuryOperated extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: TreasuryOperatedInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    externalRewards(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    treasury(overrides?: CallOverrides): Promise<[string]>;

    withdrawStake(
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  externalRewards(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

  treasury(overrides?: CallOverrides): Promise<string>;

  withdrawStake(
    amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    externalRewards(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    treasury(overrides?: CallOverrides): Promise<string>;

    withdrawStake(
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "ExternalRewardsAdded(address,address,uint256)"(
      from?: string | null,
      token?: null,
      reward?: null
    ): ExternalRewardsAddedEventFilter;
    ExternalRewardsAdded(
      from?: string | null,
      token?: null,
      reward?: null
    ): ExternalRewardsAddedEventFilter;

    "ExternalRewardsClaimed(address)"(
      receiver?: null
    ): ExternalRewardsClaimedEventFilter;
    ExternalRewardsClaimed(receiver?: null): ExternalRewardsClaimedEventFilter;

    "StakeWithdrawn(uint256)"(amount?: null): StakeWithdrawnEventFilter;
    StakeWithdrawn(amount?: null): StakeWithdrawnEventFilter;
  };

  estimateGas: {
    externalRewards(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    treasury(overrides?: CallOverrides): Promise<BigNumber>;

    withdrawStake(
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    externalRewards(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    treasury(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    withdrawStake(
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
